# Generated by Django 5.2.8 on 2025-11-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter the name of the product', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the product', max_digits=10)),
                ('sku', models.TextField(help_text='Enter SKU code', max_length=50)),
            ],
        ),
    ]
